# Generated by Django 4.0.3 on 2022-03-26 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initialcounters_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='description',
        ),
    ]
